name: Run Yahoo Finance Script Daily

on:
  schedule:
    - cron: '0 11 * * *'  # Runs every day at 4:00 PM PKT
  workflow_dispatch:  # Allows manual trigger

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Install dependencies
        run: |
          pip install pandas requests beautifulsoup4

      - name: Run Yahoo Finance script
        run: python Yahoo_Finance_Script/Yahoo_Finance_stock.py

